// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendPath(arg1, arg2) {
  return window['go']['main']['App']['AppendPath'](arg1, arg2);
}

export function Chmod(arg1, arg2) {
  return window['go']['main']['App']['Chmod'](arg1, arg2);
}

export function CreateTempFile(arg1) {
  return window['go']['main']['App']['CreateTempFile'](arg1);
}

export function DeleteEntries(arg1) {
  return window['go']['main']['App']['DeleteEntries'](arg1);
}

export function DirExists(arg1) {
  return window['go']['main']['App']['DirExists'](arg1);
}

export function FileExists(arg1) {
  return window['go']['main']['App']['FileExists'](arg1);
}

export function GetError() {
  return window['go']['main']['App']['GetError']();
}

export function GetExecutable() {
  return window['go']['main']['App']['GetExecutable']();
}

export function GetGitHubThemes() {
  return window['go']['main']['App']['GetGitHubThemes']();
}

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function GetOSName() {
  return window['go']['main']['App']['GetOSName']();
}

export function Getwd() {
  return window['go']['main']['App']['Getwd']();
}

export function MakeDir(arg1) {
  return window['go']['main']['App']['MakeDir'](arg1);
}

export function MakeFile(arg1) {
  return window['go']['main']['App']['MakeFile'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadKanban() {
  return window['go']['main']['App']['ReadKanban']();
}

export function ReadKanbanString() {
  return window['go']['main']['App']['ReadKanbanString']();
}

export function ReadTheme() {
  return window['go']['main']['App']['ReadTheme']();
}

export function ReadThemeString() {
  return window['go']['main']['App']['ReadThemeString']();
}

export function SaveKanbanBoards(arg1) {
  return window['go']['main']['App']['SaveKanbanBoards'](arg1);
}

export function SaveTheme(arg1) {
  return window['go']['main']['App']['SaveTheme'](arg1);
}

export function SplitFile(arg1) {
  return window['go']['main']['App']['SplitFile'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
