// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {fs} from '../models';
import {main} from '../models';

export function AppendPath(arg1:string,arg2:string):Promise<string>;

export function Chmod(arg1:string,arg2:fs.FileMode):Promise<void>;

export function CreateTempFile(arg1:string):Promise<string>;

export function DeleteEntries(arg1:string):Promise<void>;

export function DirExists(arg1:string):Promise<boolean>;

export function FileExists(arg1:string):Promise<boolean>;

export function GetError():Promise<string>;

export function GetExecutable():Promise<string>;

export function GetGitHubThemes():Promise<Array<main.GitHubRepos>>;

export function GetHomeDir():Promise<string>;

export function GetOSName():Promise<string>;

export function Getwd():Promise<string>;

export function MakeDir(arg1:string):Promise<void>;

export function MakeFile(arg1:string):Promise<void>;

export function Quit():Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadKanban():Promise<main.KanbanData>;

export function ReadKanbanString():Promise<string>;

export function ReadTheme():Promise<main.ThemeData>;

export function ReadThemeString():Promise<string>;

export function SaveKanbanBoards(arg1:string):Promise<void>;

export function SaveTheme(arg1:string):Promise<void>;

export function SplitFile(arg1:string):Promise<main.FileParts>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
